### ISSUE TITLE
Default Info File

### ISSUE THREAD

**Issue by danalexilewis** [danielkermode/project-starter-dan#1]
As a user,
I want to create an info file that is read from when I create new packages
So that i don't need to manually fill out the details in package.json

**Comment by danielkermode** [comment]
There's a currently a prompt that walks through customizing the package.json in a manner that is practically identical to slush-pages-react, however I like the idea of a config file that can be used for quick setup. Perhaps a `-c /path/to/config.json` that will skip the prompt and fill in the package.json?

**Comment by danalexilewis** [comment]
hmmm I was thinking of it as simple as
If a global config file is set 
- use its details in the package.json (author, licence, extra scripts etc...)
  else
- stout that the user can set it.

**Comment by danielkermode** [comment]
added a command `dank config` to set up author/node engine config details. If config is empty, user will be notified each time they run `dank`.
